WITH
TRIP_EFFICIENT AS
(
    SELECT DRIVER_ID,
    CASE
        WHEN MONTH(TRIP_DATE) < 7 THEN 'FIRST_HALF' ELSE 'SECOND_HALF' END AS HALF_YEAR,
    DISTANCE_KM/FUEL_CONSUMED AS EFFICIENCY FROM TRIPS
),
DRIVER_EFFICIENT AS
(
    SELECT DRIVER_ID,
    AVG(CASE WHEN HALF_YEAR = 'FIRST_HALF' THEN EFFICIENCY END) AS FIRST_HALF_AVG,
    AVG(CASE WHEN HALF_YEAR = 'SECOND_HALF' THEN EFFICIENCY END) AS SECOND_HALF_AVG 
    FROM TRIP_EFFICIENT 
    GROUP BY DRIVER_ID
)
SELECT D.DRIVER_ID,
        D.DRIVER_NAME,
        ROUND(DE.FIRST_HALF_AVG,2) AS FIRST_HALF_AVG,
        ROUND(DE.SECOND_HALF_AVG,2) AS SECOND_HALF_AVG,
        ROUND((SECOND_HALF_AVG - FIRST_HALF_AVG),2) AS EFFICIENCY_IMPROVEMENT
FROM DRIVERS D
JOIN DRIVER_EFFICIENT DE
ON D.DRIVER_ID = DE.DRIVER_ID
WHERE DE.FIRST_HALF_AVG IS NOT NULL AND DE.SECOND_HALF_AVG IS NOT NULL
HAVING ROUND((SECOND_HALF_AVG - FIRST_HALF_AVG),2) > 0
ORDER BY EFFICIENCY_IMPROVEMENT DESC,D.DRIVER_NAME
