WITH
VALID AS
(
    SELECT SESSION_ID,USER_ID,
            ROUND(TIME_TO_SEC(TIMEDIFF(MAX(EVENT_TIMESTAMP),MIN(EVENT_TIMESTAMP)))/60) AS TIMES,
            SUM(CASE WHEN EVENT_TYPE='scroll' THEN 1 ELSE 0 END) AS SCOUNT,
            SUM(CASE WHEN EVENT_TYPE='click' THEN 1 ELSE 0 END) AS CCOUNT,
            SUM(CASE WHEN EVENT_TYPE='purchase' THEN 1 ELSE 0 END) AS PCOUNT
    FROM APP_EVENTS
    GROUP BY USER_ID,SESSION_ID
)
SELECT SESSION_ID,USER_ID,TIMES AS SESSION_DURATION_MINUTES,SCOUNT AS SCROLL_COUNT
FROM VALID
WHERE
    SCOUNT >= 5 AND
    TIMES > 30 AND
    CCOUNT/SCOUNT < 0.20 AND
    PCOUNT = 0
ORDER BY SCROLL_COUNT DESC,SESSION_ID