SELECT * 
FROM 
    STADIUM S1
WHERE 
    PEOPLE >= 100
AND
(
    (
        EXISTS(SELECT 1 FROM STADIUM S2 WHERE S2.ID = S1.ID-1 AND S2.PEOPLE >= 100) AND
        (SELECT 1 FROM STADIUM S3 WHERE S3.ID = S1.ID+1 AND S3.PEOPLE >= 100)
    )
    OR
    (
        EXISTS(SELECT 1 FROM STADIUM S2 WHERE S2.ID = S1.ID-1 AND S2.PEOPLE >= 100) AND
        (SELECT 1 FROM STADIUM S3 WHERE S3.ID = S1.ID-2 AND S3.PEOPLE >= 100)
    )
    OR
    (
        EXISTS(SELECT 1 FROM STADIUM S2 WHERE S2.ID = S1.ID+1 AND S2.PEOPLE >= 100) AND
        (SELECT 1 FROM STADIUM S3 WHERE S3.ID = S1.ID+2 AND S3.PEOPLE >= 100)
    )
)
ORDER BY VISIT_DATE