SELECT S.PRODUCT_ID,P.FIRST_YEAR,S.QUANTITY,S.PRICE
FROM SALES S
JOIN (
    SELECT PRODUCT_ID,MIN(YEAR) AS FIRST_YEAR FROM SALES GROUP BY PRODUCT_ID
) P
ON S.PRODUCT_ID = P.PRODUCT_ID
AND S.YEAR = P.FIRST_YEAR