-- WITH
-- VALID AS
-- (
--     SELECT COUNT(*) AS TOTAL,T.STATUS AS STATUS,T.REQUEST_AT AS DAY
--     FROM TRIPS T
--     JOIN USERS UC ON T.CLIENT_ID = UC.USERS_ID AND UC.BANNED = 'No'
--     JOIN USERS UD ON T.DRIVER_ID = UD.USERS_ID AND UD.BANNED = 'No'
--     WHERE T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
--     GROUP BY T.REQUEST_AT,T.STATUS
-- )
-- SELECT DAY,ROUND(SUM(CASE WHEN STATUS LIKE 'cancelled%' THEN 1 ELSE 0 END)/SUM(TOTAL),2) AS 'CANCELLATION RATE'
-- FROM VALID GROUP BY DAY
SELECT T.REQUEST_AT AS DAY,ROUND(SUM(CASE WHEN T.STATUS LIKE 'cancelled%' THEN 1 ELSE 0 END)*1.0/COUNT(*),2)
AS 'CANCELLATION RATE'
FROM TRIPS T
JOIN USERS UC ON UC.USERS_ID = T.CLIENT_ID AND UC.BANNED = 'No'
JOIN USERS UD ON T.DRIVER_ID = UD.USERS_ID AND UD.BANNED = 'No'
WHERE T.REQUEST_AT BETWEEN '2013-10-01' AND '2013-10-03'
GROUP BY T.REQUEST_AT
ORDER BY T.REQUEST_AT