SELECT 
    B.BOOK_ID,
    B.TITLE,
    B.AUTHOR,
    B.GENRE,
    B.PAGES,
    (MAX(R.SESSION_RATING) - MIN(R.SESSION_RATING)) AS RATING_SPREAD,
    ROUND(
        SUM(CASE WHEN R.SESSION_RATING <= 2 OR R.SESSION_RATING >= 4 THEN 1 ELSE 0 END)
        / COUNT(R.SESSION_ID) + 0.0000001, 2
    ) AS POLARIZATION_SCORE
FROM READING_SESSIONS R
JOIN BOOKS B
    ON R.BOOK_ID = B.BOOK_ID
GROUP BY 
    B.BOOK_ID, B.TITLE, B.AUTHOR, B.GENRE, B.PAGES
HAVING 
    MAX(R.SESSION_RATING) >= 4
    AND MIN(R.SESSION_RATING) <= 2
    AND COUNT(R.SESSION_ID) >= 5
    AND (SUM(CASE WHEN R.SESSION_RATING <= 2 OR R.SESSION_RATING >= 4 THEN 1 ELSE 0 END)
         / COUNT(R.SESSION_ID) + 0.0000001) >= 0.6
ORDER BY 
    POLARIZATION_SCORE DESC,
    B.TITLE DESC;
