# Write your MySQL query statement below
SELECT ROUND((COUNT(DISTINCT A.PLAYER_ID))/
            (SELECT COUNT(DISTINCT PLAYER_ID) FROM ACTIVITY),2) AS FRACTION
FROM ACTIVITY A
JOIN
(
    SELECT PLAYER_ID,MIN(EVENT_DATE) AS FL FROM ACTIVITY GROUP BY PLAYER_ID
) AS FLS

ON
    A.PLAYER_ID = FLS.PLAYER_ID
WHERE A.EVENT_DATE = DATE_ADD(FLS.FL,INTERVAL 1 DAY)