# Write your MySQL query statement below
SELECT ROUND(100 * SUM(CASE WHEN ORDER_DATE = CUSTOMER_PREF_DELIVERY_DATE THEN 1 ELSE 0 END) / COUNT(*),2) AS IMMEDIATE_PERCENTAGE
FROM (SELECT D.DELIVERY_ID,D.CUSTOMER_ID,D.ORDER_DATE,D.CUSTOMER_PREF_DELIVERY_DATE
FROM DELIVERY D
JOIN (SELECT CUSTOMER_ID,MIN(ORDER_DATE) AS F_ORDER FROM DELIVERY GROUP BY CUSTOMER_ID) AS F
ON F.CUSTOMER_ID = D.CUSTOMER_ID AND F.F_ORDER = D.ORDER_DATE) X
