# Write your MySQL query statement below
SELECT B.BOOK_ID,B.TITLE,B.AUTHOR,B.GENRE,B.PUBLICATION_YEAR,COUNT(R.BOOK_ID) AS CURRENT_BORROWERS
FROM
    BORROWING_RECORDS R
LEFT JOIN
    LIBRARY_BOOKS B
ON
    B.BOOK_ID = R.BOOK_ID
AND
    R.RETURN_DATE IS NULL
GROUP BY
    B.BOOK_ID,B.TITLE,B.AUTHOR,B.GENRE,B.PUBLICATION_YEAR,B.TOTAL_COPIES
HAVING
    B.TOTAL_COPIES - COUNT(R.BOOK_ID) = 0
ORDER BY
    CURRENT_BORROWERS DESC,TITLE ASC