WITH
ALLMAPS AS
(SELECT
CASE 
    WHEN MONTH(S.SALE_DATE) IN (12,1,2) THEN 'Winter'
    WHEN MONTH(S.SALE_DATE) IN (3,4,5) THEN 'Spring'
    WHEN MONTH(S.SALE_DATE) IN (6,7,8) THEN 'Summer'
    WHEN MONTH(S.SALE_DATE) IN (9,10,11) THEN 'Fall'
END AS SEASON,
P.CATEGORY,
SUM(S.QUANTITY) AS TOTAL_QUANTITY,
SUM(S.QUANTITY * S.PRICE) AS TOTAL_REVENUE
FROM SALES S
JOIN PRODUCTS P ON P.PRODUCT_ID = S.PRODUCT_ID
GROUP BY SEASON,P.CATEGORY),

RANKED AS(SELECT *, ROW_NUMBER()OVER(PARTITION BY SEASON ORDER BY TOTAL_QUANTITY DESC,TOTAL_REVENUE DESC) AS RN FROM ALLMAPS)

SELECT SEASON,CATEGORY,TOTAL_QUANTITY,TOTAL_REVENUE FROM RANKED WHERE RN = 1