SELECT S.USER_ID,
    ROUND(COALESCE(SUM(CASE WHEN C.ACTION = 'confirmed' THEN 1 ELSE 0 END)*1.0/COUNT(C.USER_ID),0),2) AS CONFIRMATION_RATE
FROM SIGNUPS S
LEFT JOIN CONFIRMATIONS C
ON S.USER_ID = C.USER_ID GROUP BY S.USER_ID