# Write your MySQL query statement below
WITH
TEST AS
(
    SELECT ID,NAME,DEPARTMENTID,SALARY,
    DENSE_RANK()
    OVER(PARTITION BY DEPARTMENTID ORDER BY SALARY DESC) AS RNK
    FROM EMPLOYEE
    GROUP BY ID,NAME,DEPARTMENTID,SALARY
)
SELECT D.NAME AS DEPARTMENT,T.NAME AS EMPLOYEE,T.SALARY AS SALARY
FROM TEST T
JOIN DEPARTMENT D
ON T.DEPARTMENTID = D.ID
WHERE T.RNK < 4