SELECT P1.PRODUCT_ID AS PRODUCT1_ID,
       P2.PRODUCT_ID AS PRODUCT2_ID,
       I1.CATEGORY AS PRODUCT1_CATEGORY,
       I2.CATEGORY AS PRODUCT2_CATEGORY,
       COUNT(P1.USER_ID) AS CUSTOMER_COUNT
FROM PRODUCTPURCHASES P1
JOIN PRODUCTPURCHASES P2 ON P1.USER_ID = P2.USER_ID AND P1.PRODUCT_ID < P2.PRODUCT_ID
LEFT JOIN PRODUCTINFO I1 ON P1.PRODUCT_ID = I1.PRODUCT_ID
LEFT JOIN PRODUCTINFO I2 ON P2.PRODUCT_ID = I2.PRODUCT_ID
GROUP BY P1.PRODUCT_ID,P2.PRODUCT_ID
HAVING COUNT(*) >= 3
ORDER BY CUSTOMER_COUNT DESC,PRODUCT1_ID,PRODUCT2_ID