SELECT PCOUNT.P1_ID AS PRODUCT1_ID,
        PCOUNT.P2_ID AS PRODUCT2_ID,
        I1.CATEGORY AS PRODUCT1_CATEGORY,
        I2.CATEGORY AS PRODUCT2_CATEGORY,
        PCOUNT.CUSTOMER_COUNT
FROM 
(SELECT P1_ID, P2_ID, COUNT(DISTINCT PU_ID) AS CUSTOMER_COUNT 
FROM
(SELECT P1.USER_ID AS PU_ID,P1.PRODUCT_ID AS P1_ID,P2.PRODUCT_ID AS P2_ID
FROM
    PRODUCTPURCHASES P1
JOIN
    PRODUCTPURCHASES P2
ON
    P1.USER_ID = P2.USER_ID AND P1.PRODUCT_ID < P2.PRODUCT_ID ) AS PAIR_PURCHASE
GROUP BY P1_ID,P2_ID
HAVING COUNT(*) >= 3)AS PCOUNT
JOIN PRODUCTINFO I1
ON PCOUNT.P1_ID = I1.PRODUCT_ID
JOIN PRODUCTINFO I2
ON PCOUNT.P2_ID = I2.PRODUCT_ID
ORDER BY customer_count DESC, product1_id, product2_id;