# Write your MySQL query statement below
SELECT MACHINE_ID,
    ROUND(AVG(ET-ST),3) AS PROCESSING_TIME
    FROM (SELECT MACHINE_ID,PROCESS_ID,
            MAX(CASE WHEN ACTIVITY_TYPE = 'end' THEN TIMESTAMP END) AS ET,
            MIN(CASE WHEN ACTIVITY_TYPE = 'start' THEN TIMESTAMP END) AS ST FROM ACTIVITY GROUP BY MACHINE_ID,PROCESS_ID) AS X
GROUP BY
    MACHINE_ID