# Write your MySQL query statement below
WITH
COMBINE AS
(
    SELECT U.NAME
    FROM MOVIERATING MR
    JOIN USERS U ON U.USER_ID = MR.USER_ID
    JOIN MOVIES M ON M.MOVIE_ID = MR.MOVIE_ID
    GROUP BY U.NAME
    ORDER BY COUNT(*) DESC, U.NAME ASC
    LIMIT 1
),
RATING AS
(
    SELECT M.TITLE,AVG(MR.RATING) AS AVERAGE
    FROM MOVIERATING MR
    JOIN MOVIES M
    ON MR.MOVIE_ID = M.MOVIE_ID
    WHERE DATE_FORMAT(MR.CREATED_AT, '%Y-%m') = '2020-02' 
    GROUP BY M.TITLE
    ORDER BY AVERAGE DESC,M.TITLE ASC
    LIMIT 1
)
SELECT NAME AS RESULTS
FROM COMBINE
UNION ALL
SELECT TITLE FROM RATING