# Write your MySQL query statement below
WITH XY AS(
    SELECT DEPARTMENTID,MAX(SALARY) AS MS FROM EMPLOYEE GROUP BY DEPARTMENTID
)
SELECT D.NAME AS DEPARTMENT,E.NAME AS EMPLOYEE,E.SALARY AS SALARY
FROM
    EMPLOYEE E
JOIN
    XY X
ON
    E.DEPARTMENTID = X.DEPARTMENTID AND E.SALARY = X.MS
JOIN 
    DEPARTMENT D
ON
    E.DEPARTMENTID = D.ID