# Write your MySQL query statement below
#(SELECT * FROM QUEUE ORDER BY TURN GROUP BY TURN)
WITH CTE AS(
    SELECT PERSON_NAME,WEIGHT,TURN,SUM(WEIGHT) OVER (ORDER BY TURN ASC) AS TOTAL FROM QUEUE
),
VALID AS (SELECT * FROM CTE WHERE TOTAL <= 1000)
SELECT PERSON_NAME FROM VALID
ORDER BY TURN DESC
LIMIT 1